### GET request to example server
POST localhost:8080/records/_doc/t3_erf4dp
Authorization: Basic user:pass
Content-Type: application/json

{
  "id": "t3_erf4dp",
  "artist": "PinkPantheress"
}

###

POST localhost:8080/records/_update/t3_erf4dp
Content-Type: application/json

{
  "id": "t3_erf4dp",
  "artist": "PinkPantheress"
}

###

GET https://spin-service.execute-api.us-west-2.amazonaws.com/prod/search/search?q=playboi&release_title=whole

###

GET https://api.discogs.com/database/search?q=The%20Residents%20Randy%20Chuck%20Bob
Authorization: Discogs token=

###
GET https://www.roughtrade.com/de/product/djo/decide-2#50485054374219

###

POST http://api.spinmyrecords.com/raw
Content-Type: application/json


###
GET https://api.discogs.com/database/search?q=PinkPantheress%20%E2%80%93%20To%20Hell%20With%20It